#ifndef INTERRUPTS_H
#define INTERRUPTS_H
		
#include "cytypes.h"

CY_ISR_PROTO(ADC_EOC);
CY_ISR_PROTO(OSC_0_OVF_VECT);
CY_ISR_PROTO(OSC_1_OVF_VECT);
CY_ISR_PROTO(OSC_2_OVF_VECT);
CY_ISR_PROTO(OSC_3_OVF_VECT);
CY_ISR_PROTO(ENV_0_OVF_VECT);
CY_ISR_PROTO(ENV_1_OVF_VECT);
CY_ISR_PROTO(ENV_2_OVF_VECT);
CY_ISR_PROTO(ENV_3_OVF_VECT);

#endif
/* [] END OF FILE */
